#! /usr/bin/env sh

# bspc monitor -d I II III IV V VI VII VIII IX X
# bspc monitor -d 01 02 03 04 05 06 07 08 09 10
# bspc monitor -d   ﴀ      辶 

num_mon=$(bspc query -M | wc -l)

## single monitor setup
[ $num_mon -lt 2 ] && bspc monitor -d 01 02 03 04 05 06 07 08 09 10

## dual monitor configuration
if [ $num_mon -gt 2 ]; then
    bspc monitor eDP1 -d 01 02 03 04 05 06 
    bspc monitor HDMI1 07 08 09 10
fi

bspc config border_width         3
bspc config window_gap          16

bspc config split_ratio          0.54
bspc config borderless_monocle   true
bspc config gapless_monocle      true

## cleanup unmanaged windows
bspc -o


# bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a Chromium desktop='^2'
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off
bspc rule -a 'Filemanager' state=floating follow=on
bspc rule -a 'Filesearch' state=floating follow=on
