#! /usr/bin/env sh
while pgrep -u $UID -x bspwmrc >/dev/null; do sleep 1; done

## source color scheme
. $HOME/.cache/themes/light_world/colors.sh

## source lemonbar properties
. $HOME/src/bspwm/lemonbar/panel_options

## global variables
## set colors
bspc config normal_border_color $COLOR1
bspc config focused_border_color $COLOR11
bspc config presel_feedback_color $COLOR11

## check monitor count on launch
num_mon=$(bspc query -M | wc -l)

## tag templates
# bspc monitor -d I II III IV V VI VII VIII IX X
# bspc monitor -d 01 02 03 04 05 06 07 08 09 10
# bspc monitor -d 01 02 03 04 05 06
# bspc monitor -d   ﴀ      辶 

## single monitor setup
if [ $num_mon -lt 2 ]; then
    bspc monitor eDP1 -d 01 02 03 04 05 06
else
    ## dual monitor configuration
    bspc monitor HDMI1 -d 01 02 03 04
    bspc monitor eDP1 -d 05 06
fi

bspc config bottom_padding $PANEL_HEIGHT

bspc config border_width         4
bspc config window_gap           16
bspc config split_ratio          0.50
bspc config single_monocle       true
bspc config gapless_monocle      false
bspc config borderless_monocle   true

. $HOME/.config/bspwm/rules
