#! /usr/bin/env sh

## source color scheme
. $HOME/.cache/themes/dark_world/dark/colors.sh

## launch panel execution
$HOME/src/bspwm/panel/panel &

## global variables
## set colors
bspc config normal_border_color $COLOR1
bspc config focused_border_color $COLOR15
bspc config presel_feedback_color $COLOR7

## check monitor count on launch
num_mon=$(bspc query -M | wc -l)

## tag templates
# bspc monitor -d I II III IV V VI VII VIII IX X
# bspc monitor -d 01 02 03 04 05 06 07 08 09 10
# bspc monitor -d 01 02 03 04 05 06
# bspc monitor -d   ﴀ      辶 

## single monitor setup
[ $num_mon -lt 2 ] && bspc monitor -d 01 02 03 04 05 06

## dual monitor configuration
if [ $num_mon -gt 2 ]; then
    bspc monitor eDP1 -d 01 02 03 04
    bspc monitor HDMI1 -d 05 06
fi

bspc config top_padding          34

bspc config border_width         4
bspc config window_gap           16
bspc config split_ratio          0.50
bspc config single_monocle       true
bspc config borderless_monocle   true
bspc config gapless_monocle      true

. $HOME/.config/bspwm/rules
