#! /usr/bin/env sh

get_volume() {
    while true; do
        muted=$(pamixer --sink 0 --get-mute)
        vol=$(volume)

        if $muted = true; then
            printf 'V%s\n' "ﱝ MUTED"
        else
            printf 'V%s%%\n' "墳 $vol"
        fi
        sleep 1
    done
}

