#! /usr/bin/env sh

get_volume() {
    muted=$(pamixer --sink 0 --get-mute)
    vol=$(volume)

    if $muted = true; then
        printf 'V%s\n' " muted"
    else
        printf 'V%s%%\n' " $vol"
    fi
}

