#! /usr/bin/env sh

## kill processes
killall -9 lemonbar
killall -9 xdo
killall -9 xtitle

## include color scheme
. $HOME/.cache/themes/light_world/colors.sh

## lemonbar variables
. $HOME/src/bspwm/lemonbar/panel_options

## include modules
. $HOME/src/bspwm/lemonbar/modules/datetime
. $HOME/src/bspwm/lemonbar/modules/bspwm
. $HOME/src/bspwm/lemonbar/modules/battery
. $HOME/src/bspwm/lemonbar/modules/volume


## manage panel fifo
[ -e "$PANEL_FIFO" ] && rm "$PANEL_FIFO"
mkfifo "$PANEL_FIFO"

get_battery > "$PANEL_FIFO" &
get_datetime > "$PANEL_FIFO" &
get_volume > "$PANEL_FIFO" &
bspc subscribe report > "$PANEL_FIFO" &

statusline() {
    while read -r line ; do
        case $line in
            B*)
                battery="%{F$FOREGROUND}%{B$BACKGROUND} ${line#?} %{B-}%{F-}"
                ;;
            D*)
                datetime="%{F$FOREGROUND}%{B$BACKGROUND} ${line#?} %{B-}%{F-}"
                ;;
            V*)
                volume="%{F$FOREGROUND}%{B$BACKGROUND} ${line#?} %{B-}%{F-}"
              ;;
            W*)
                # bspwm's state
                IFS=':'
                set -- ${line#?}
                wm=$(get_bspwm_state $line)
                ;;
        esac

        main_screen="%{l}${wm}%{c}${datetime}%{r} ${volume} ${battery} "
        off_screen="%{l}${wm}%{c}${datetime}%{r} "

        if [ "$(bspc query -M | wc -l)" -gt 1 ]; then
            printf '%s %s\n' "%{S0}$off_screen" "%{S1}$main_screen"
        else
            printf '%s\n' "%{S0}$main_screen"
        fi
    done
}

statusline < "$PANEL_FIFO" | lemonbar -a 10 -b -p \
        -g x"$PANEL_HEIGHT" \
        -n "$PANEL_WM_NAME"  \
        -f "$FONT" \
        -F "$FOREGROUND" -B "$BACKGROUND" | dash &

until wid=$(xdo id -m -a "$PANEL_WM_NAME"); do
    sleep 1
done

xdo below -t $(xdo id -n root) $wid &
