#! /usr/bin/env sh

## include color scheme
. $HOME/.cache/themes/light_world/colors.sh
. $HOME/src/bspwm/lemonbar/panel_options

## Just to make sure there is no double process
pkill -9 -f xtitle
pkill -9 -f xdo

# setup global variables
FONT="Hermit:style=regular:size=11:antialias=true"
ICON_FONT="ShureTechMono Nerd Font:size=11:antialias=true"

## lemonbar variables
PANEL_WM_NAME=bspwm_panel
PANEL_FIFO=/tmp/panel-fifo

## include modules
. $HOME/src/bspwm/lemonbar/modules/datetime
. $HOME/src/bspwm/lemonbar/modules/xtitle
. $HOME/src/bspwm/lemonbar/modules/bspwm
. $HOME/src/bspwm/lemonbar/modules/battery
. $HOME/src/bspwm/lemonbar/modules/volume


## manage panel fifo
[ -e "$PANEL_FIFO" ] && rm "$PANEL_FIFO"
mkfifo "$PANEL_FIFO"

modules() {
    while true; do
        get_battery 
        get_datetime
        get_title 
        get_volume
        sleep 0.5
    done
}

modules > "$PANEL_FIFO" &
bspc subscribe report > "$PANEL_FIFO" &

statusline() {
    while read -r line ; do
        case $line in
            B*)
                battery="%{F$FOREGROUND}%{B$BACKGROUND} ${line#?} %{B-}%{F-}"
                ;;
            D*)
                datetime="%{F$FOREGROUND}%{B$BACKGROUND} ${line#?} %{B-}%{F-}"
                ;;
            T*)
                title="%{F$FOREGROUND}%{B$BACKGROUND} ${line#?} %{B-}%{F-}"
                ;;
            V*)
                volume="%{F$FOREGROUND}%{B$BACKGROUND} ${line#?} %{B-}%{F-}"
              ;;
            W*)
                # bspwm's state
                wm=
                IFS=':'
                set -- ${line#?}
                wm=$(get_bspwm_state $line)
                ;;
        esac

        main_screen="%{l}${wm}%{c}${datetime}%{r}[${title}] ${volume} ${battery}"
        off_screen="%{l}${wm}%{c}${datetime}%{r}${title}"

        if [ "$(bspc query -M | wc -l)" -gt 1 ]; then
            printf '%s %s\n' "%{S0}$off_screen" "%{S1}$main_screen"
        else
            printf '%s\n' "%{S0}$main_screen"
        fi
    done
}

statusline < "$PANEL_FIFO" | lemonbar -a 10 -b -p \
        -g "$PANEL_WIDTH"x"$PANEL_HEIGHT"+"$PANEL_X_OFFSET"+"$PANEL_Y_OFFSET" \
        -n "$PANEL_WM_NAME"  \
        -f "$FONT" -o 2  -f "$ICON_FONT" -o -2 \
        -F "$FOREGROUND" -B "$BACKGROUND" | sh &

wid=$(xdo id -m -a "$PANEL_WM_NAME")
xdo below -t $(xdo id -n root) $wid &

wait
