#! /usr/bin/env sh

WINDOW_GAP=$(bspc config window_gap)

MAX_GAP_CAP=40

usage() {
    >&1 printf '%s \n' 'usage: changegap [-i] [-d] [-s] value' ;
    exit 1
}

inc() {
    NEW_GAP=$(( $WINDOW_GAP + $1 ))
    if [ $NEW_GAP -gt $MAX_GAP_CAP ]; then
        exit 0
    else
        bspc config window_gap $NEW_GAP
    fi

}

dec() {
    NEW_GAP=$(( $WINDOW_GAP - $1 ))
    if [ $NEW_GAP -eq 0 ]; then
        exit 0
    elif [ $NEW_GAP -lt 1 ]; then
        bspc config window_gap $NEW_GAP
        exit 0
    else
        bspc config window_gap $NEW_GAP
    fi
}

_set() {
    bspc config window_gap $1
}

case "$1" in
    inc|-i) inc "$2" ;;
    dec|-d) dec "$2" ;;
    set|-s) _set "$2" ;;
    -h) usage ;;
esac
    
