#! /usr/bin/env sh

# Just to make sure there is no double process
killall -9 lemonbar xtitle xdo datetime

## include color scheme
. $HOME/.cache/themes/dark_world/dark/colors.sh

## include modules
. $HOME/src/bspwm/panel/modules/datetime
. $HOME/src/bspwm/panel/modules/xtitle
. $HOME/src/bspwm/panel/modules/bspwm

# setup global variables
FONT="Hermit:style=regular:size=11"
ICON_FONT="ShureTechMono Nerd Font:size=11"

## lemonbar variables
. $HOME/src/bspwm/panel/panel_one
PANEL_WM_NAME=bspwm_panel
PANEL_FIFO=/tmp/panel-fifo

[ -e "$PANEL_FIFO" ] && rm "$PANEL_FIFO"
mkfifo "$PANEL_FIFO"

get_datetime > "$PANEL_FIFO" &
# get_volume > "$PANEL_FIFO" &
# get_battery > "$PANEL_FIFO" &
# get_backlight > "$PANEL_FIFO" &
get_title > "$PANEL_FIFO" &

bspc subscribe report > "$PANEL_FIFO" &

statusline() {
    while read -r line ; do
        case $line in
            S*)
                # clock output
                sys="%{F$FOREGROUND}%{B$BACKGROUND} ${line#?} %{B-}%{F-}"
                ;;
            T*)
                # xtitle output
                title="%{F$FOREGROUND}%{B$BACKGROUND} ${line#?} %{B-}%{F-}"
                ;;
            W*)
                # bspwm's state
                wm=
                IFS=':'
                set -- ${line#?}
                wm=$(get_bspwm_state $line)
                ;;
        esac

        printf "%s\n" "%{l} ${wm}%{c}${title}%{r}${sys} "
    done
}

statusline < "$PANEL_FIFO" | lemonbar -a 32 -u 2 \
    -g "$PANEL_WIDTH"x"$PANEL_HEIGHT"+"$X_OFFSET"+"$Y_OFFSET" \
        -n "$PANEL_WM_NAME"  \
        -o 2 -f "$FONT" -o 2 -f "$ICON_FONT" \
        -F "$FOREGROUND" -B "$BACKGROUND" | dash &

sleep 1

wid=$(xdo id -m -a "$PANEL_WM_NAME")
xdo above -t "$(xdo id -N Bspwm -n root | sort | head -n 1)" "$wid"

wait
