#! /usr/bin/env sh

# Just to make sure there is no double process
killall -9 lemonbar xtitle xdo datetime

## include color scheme
. $HOME/.cache/themes/light_world/colors.sh
# setup global variables
FONT="Hermit:style=regular:size=11"
ICON_FONT="ShureTechMono Nerd Font:size=11"

## lemonbar variables
PANEL_WM_NAME=bspwm_panel
PANEL_FIFO=/tmp/panel-fifo

[ -e "$PANEL_FIFO" ] && rm "$PANEL_FIFO"
mkfifo "$PANEL_FIFO"

## include modules
. $HOME/src/bspwm/panel/modules/datetime
. $HOME/src/bspwm/panel/modules/xtitle
. $HOME/src/bspwm/panel/modules/bspwm
# . $HOME/src/bspwm/panel/modules/battery


get_datetime > "$PANEL_FIFO" &
# get_volume > "$PANEL_FIFO" &
# get_battery > "$PANEL_FIFO" &
# get_backlight > "$PANEL_FIFO" &
get_title > "$PANEL_FIFO" &

bspc subscribe report > "$PANEL_FIFO" &

statusline() {
    while read -r line ; do
        case $line in
            S*)
                # clock output
                sys="%{F$FOREGROUND}%{B$BACKGROUND} ${line#?} %{B-}%{F-}"
                ;;
            T*)
                # xtitle output
                title="%{F$FOREGROUND}%{B$BACKGROUND} ${line#?} %{B-}%{F-}"
                ;;
            W*)
                # bspwm's state
                wm=
                IFS=':'
                set -- ${line#?}
                wm=$(get_bspwm_state $line)
                ;;
        esac

        layout="%{l}${wm}%{c}${title}%{r}${sys}"

        if [ "$(bspc query -M | wc -l)" -gt 1 ]; then
            printf '%s%s\n' "%{S0}$layout" "%{S1}$layout"
        else
            printf '%s\n' "%{S0}$layout"
        fi
    done
}

statusline < "$PANEL_FIFO" | lemonbar -a 32 -b \
        -g x"$PANEL_HEIGHT" \
        -n "$PANEL_WM_NAME"  \
        -o 2 -f "$FONT" -o 2 -f "$ICON_FONT" \
        -F "$FOREGROUND" -B "$BACKGROUND" | sh &

until wid=$(xdo id -m -a "$PANEL_WM_NAME"); do
    sleep 0.1
done

xdo above -t "$(xdo id -N Bspwm -n root | sort | head -n 1)" "$wid" &
