#! /usr/bin/env sh

# Just to make sure there is no double process
killall -9 lemonbar xtitle xdo datetime

## include color scheme
. $HOME/.cache/themes/dark_world/dark/colors.sh

## include modules
. $HOME/src/bspwm/panel/modules/datetime
. $HOME/src/bspwm/panel/modules/xtitle
. $HOME/src/bspwm/panel/modules/bspwm

# setup global variables
FONT="xft:xos4\ Terminus:size=12"
ICON_FONT="xft:ShureTechMono\ Nerd\ Font:size=12"

WIDTH=1920

PANEL_HORIZONTAL_OFFSET=250
PANEL_VERTICAL_OFFSET=$(( $(bspc config window_gap) / 2 ))

PANEL_HEIGHT=28
PANEL_WIDTH=$(( $WIDTH - $(( 2 * $PANEL_HORIZONTAL_OFFSET )) ))

PANEL_WM_NAME=bspwm_panel
PANEL_FIFO=/tmp/panel-fifo

export PANEL_HEIGHT PANEL_VERTICAL_OFFSET

[ -e "$PANEL_FIFO" ] && rm "$PANEL_FIFO"
mkfifo "$PANEL_FIFO"

get_datetime > "$PANEL_FIFO" &
get_title > "$PANEL_FIFO" &

bspc subscribe report > "$PANEL_FIFO" &

num_mon=$(bspc query -M | wc -l)

statusline() {
    while read -r line ; do
        case $line in
            S*)
                # clock output
                sys="%{F$FOREGROUND}%{B$BACKGROUND} ${line#?} %{B-}%{F-}"
                ;;
            T*)
                # xtitle output
                title="%{F$FOREGROUND}%{B$BACKGROUND} ${line#?} %{B-}%{F-}"
                ;;
            W*)
                # bspwm's state
                wm=
                IFS=':'
                set -- ${line#?}
                wm=$(get_bspwm_state $line)
                ;;
        esac

        printf "%s\n" "%{l}${wm}%{c}${title}%{r}${sys}"
    done
}

statusline < "$PANEL_FIFO" | lemonbar -a 32 -u 2 \
        -g "$PANEL_WIDTH"x"$PANEL_HEIGHT"+"$PANEL_HORIZONTAL_OFFSET"+"$PANEL_VERTICAL_OFFSET" \
        -n "$PANEL_WM_NAME"  \
        -o 3 -f "$FONT" -o 3 -f "$ICON_FONT" \
        -F "$FOREGROUND" -B "$BACKGROUND" | dash &

sleep 1

wid=$(xdo id -m -a "$PANEL_WM_NAME")
xdo above -t "$(xdo id -N Bspwm -n root | sort | head -n 1)" "$wid"

wait
